### ISSUE TITLE
How to connect servers?

### ISSUE THREAD

**Issue by denfry** [Doctacosa/IOSync#3]
I have two paper 1.21 servers with IOSync  on it, I set custom path in storage-path, and when you connect to other server inventory of the player doesn't saves and loads on another server, can you help me maybe I set up something incorrect

**Comment by Doctacosa** [comment]
Let's say you have two servers, in directories called `server-a` and `server-b`. You need a common path to put profiles in, I call mine `players` and place it right next to the servers. In this case, your directory structure will look like this:
- `players/`
- `server-a/`
- `server-b/`

From there, here's the minimal content of `config.yml` to make it work:
```
storage-path: ../players/
```

And that's it! As players start joining and leaving your servers, the content of the `players` directory will gradually fill out with their shared inventories.

**Comment by denfry** [comment]
can we go to discord so I can explain what it looks like to me?

**Comment by denfry** [comment]
I suppose the problem is that I have these servers on hosting and they are not in the same partition, but for each of them a different partition is created and I do not understand where to store the data.

**Comment by Doctacosa** [comment]
Ah, Minecraft hosting. The two could be installed on the same hardware, but in different accounts, so they don't see each other. In this case, it won't work as-is.

You can always try to ask your host if they could make a directory from account-a accessible to account-b. Let's say you create a directory named `players/` inside of account-a. If its full path is in `/home/account-a/players/`, you ask your host to make this read-writable for both accounts. Then you configure both plugins to point to that same address, and it could work.

If both servers are on different hardware entirely, this isn't supported at the moment and won't work for you.

**Comment by denfry** [comment]
Thanks for your help! I will try to solve the issue with hosting
